# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-28 23:22
from __future__ import unicode_literals

from django.db import migrations

def insert_sites(apps, schema_editor):
    """Populate the sites model"""
    Site = apps.get_model('sites', 'Site')
    Site.objects.all().delete()

    # Register SITE_ID = 1
    Site.objects.create(domain='indicoapp.com', name='indico')
    

class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(insert_sites)
    ]
